admin_homepage:
    path:     /admin
    defaults: { _controller: AdminBundle:Index:index }
admin_article:
    path:     /admin/article
    defaults: { _controller: AdminBundle:Article:index }
admin_test:
    path:     /admin/test
    defaults: { _controller: AdminBundle:Article:test }
admin_update_article:
    path:     /admin/article/update/{id}
    defaults: { _controller: AdminBundle:Article:update }
    requirements:
            id: \d*
admin_create_article:
    path:     /admin/article/create/{idImage}/{idLocalisation}
    defaults: { _controller: AdminBundle:Article:create }
    requirements:
            idImage: \d*
            idLocalisation: \d*
admin_create_localisation:
    path:     /admin/article/createlocalisation
    defaults: { _controller: AdminBundle:Article:create_localisation }
admin_create_img:
    path:     /admin/article/createimage/{idLocalisation}
    defaults: { _controller: AdminBundle:Article:create_img }
    requirements:
            idLocalisation: \d*
admin_delete_article:
    path:     /admin/article/delete/{id}
    defaults: { _controller: AdminBundle:Article:delete}
    requirements:
            id: \d*
admin_read_article:
    path:     /admin/article/read/{id}
    defaults: { _controller: AdminBundle:Article:read }
    requirements:
            id: \d*
admin_user:
    path:     /admin/user
    defaults: { _controller: AdminBundle:Utilisateur:index }
admin_delete_com:
    path:     /admin/com/delete/{id}
    defaults: { _controller: AdminBundle:Utilisateur:deleteCom }
    requirements:
            id: \d*
admin_validate_com:
    path:     /admin/com/validate/{id}
    defaults: { _controller: AdminBundle:Utilisateur:validateCom }
    requirements:
            id: \d*