ibn_khaldoun_user:
    resource: "@IbnKhaldounUserBundle/Resources/config/routing.yml"
    prefix:   /

entity:
    resource: "@EntityBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /

public:
    resource: "@PublicBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
login:
    path:   /login
    defaults:  { _controller: IbnKhaldounUserBundle:Security:login }

login_check:
    path:   /login_check

logout:
    path:   logout