public_homepage:
    path:     /
    defaults: { _controller: PublicBundle:IbnkhaldounMap:index }
public_map:
    path:     /parcours
    defaults: { _controller: PublicBundle:IbnkhaldounMap:map}
public_article:
    path:     /article
    defaults: { _controller: PublicBundle:Article:index}
public_decouvrir:
    path:     /decouvrir
    defaults: { _controller: PublicBundle:Article:decouvrir}
public_readarticle:
    path:     /article/read/{id}
    defaults: { _controller: PublicBundle:Article:read}
    requirements:
        id: \d*
public_getjsonarticle:
    path:     /article/getjsonarticles/{year}
    defaults:
        _controller: PublicBundle:Article:getjsonarticles
        format: json
    requirements:
        year:   \d{4}